@host = http://localhost:5001

###
GET {{host}}
###
GET {{host}}/ping
###
POST {{host}}/ping
###
OPTIONS {{host}}/ping
###
GET {{host}}/products
###
GET {{host}}/product/4
###
GET {{host}}/comments/product/2
### 
GET {{host}}/comments/product/1
